/// Generated by AssetsRefGenerator on 2022/03/12
class Res {
  static const String back_ground = "assets/images/back_ground.png";
  static const String correct = "assets/images/correct.png";
  static const String door_closed = "assets/images/door_closed.png";
  static const String door_open = "assets/images/door_open.png";
  static const String lamp_closed = "assets/images/lamp_closed.png";
  static const String lamp_opend = "assets/images/lamp_opend.png";
  static const String logo = "assets/images/logo.png";
  static const String POORICH = "assets/fonts/POORICH.TTF";
}
